# Generated by Django 6.0.4 on 2026-05-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensordata_ph'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='crop_type',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
