# Generated by Django 6.0.4 on 2026-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_farm_address_farm_crop_type_farm_soil_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
